### ISSUE TITLE
Is there an example of how we can define custom validation rules?

### ISSUE THREAD

**Issue by FamilyMan** [sfxcode/formkit-primevue-nuxt#1]
Sorry for creating an issue for this, I couldn't see a questions option.

Is there a way to add custom validation rules?

If I add /plugins/formkit.ts with

```
import { defaultConfig, plugin } from '@formkit/vue'
import isRange from '~/rules/isRange'

export default defineNuxtPlugin({
  parallel: true,
  setup: (nuxtApp) => {
    nuxtApp.vueApp.use(plugin, defaultConfig({
      rules: { isRange },
    }))
  },
})
```

and rules/isRange.ts

```
const isRange = function (node) {
  return node.value.length === 2
}

export default isRange
```

I don't know if this code is correct, but I also get:

WARN: Plugin has already been applied to target app.

**Comment by sfxcode** [comment]
HI, add some text in the README.

best way for custom config is a nuxt plugin that contains at least the primeInputs configuration.

eg:

```ts
import { defaultConfig, plugin } from '@formkit/vue'
import { primeInputs, primeOutputs } from '@sfxcode/formkit-primevue'

export default defineNuxtPlugin((nuxtApp) => {
  // Doing something with nuxtApp
  const app = nuxtApp.vueApp
  app.use(plugin, defaultConfig({
    inputs: { ...primeInputs, ...primeOutputs },
    // ... additional configurations like locales, plugins, custom validations etc.
  }))
})
```

Also you have to ensure to disable the configuration provided in this plugin.

```
  formkitPrimevue: {
    formkitAutoConfig: false
}
```

Latest version should also fix the warning problem.

Hope that helps,

Greetings Tom

**Comment by FamilyMan** [comment]
Excellent, thank you!
